# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(844, 485)
        MainWindow.setMinimumSize(QSize(844, 485))
        MainWindow.setMaximumSize(QSize(844, 485))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.actionSalir = QAction(MainWindow)
        self.actionSalir.setObjectName(u"actionSalir")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 321, 241))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 91, 21))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 210, 55, 20))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.label_3.setFont(font1)
        self.label_estadoPro = QLabel(self.frame)
        self.label_estadoPro.setObjectName(u"label_estadoPro")
        self.label_estadoPro.setGeometry(QRect(70, 210, 141, 21))
        self.label_estadoPro.setFont(font1)
        self.pushButton_4 = QPushButton(self.frame)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QRect(10, 40, 301, 161))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        font2.setWeight(75)
        self.pushButton_4.setFont(font2)
        self.pushButton_4.setStyleSheet(u"")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(510, 10, 321, 241))
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 111, 21))
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 210, 55, 16))
        self.label_4.setFont(font1)
        self.label_estadoCon = QLabel(self.frame_2)
        self.label_estadoCon.setObjectName(u"label_estadoCon")
        self.label_estadoCon.setGeometry(QRect(80, 210, 111, 21))
        self.label_estadoCon.setFont(font1)
        self.pushButton_5 = QPushButton(self.frame_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QRect(10, 40, 301, 161))
        self.pushButton_5.setFont(font2)
        self.pushButton_5.setStyleSheet(u"")
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(340, 10, 161, 241))
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 10, 111, 21))
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 71, 21))
        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 110, 101, 21))
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 170, 101, 21))
        self.pushButton = QPushButton(self.frame_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QRect(10, 70, 118, 35))
        self.pushButton.setStyleSheet(u"")
        self.pushButton_2 = QPushButton(self.frame_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QRect(10, 130, 118, 35))
        self.pushButton_2.setStyleSheet(u"QPushButton{\n"
"	background-color: rgb(85, 170, 0);\n"
"	border: None;\n"
"}")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_3 = QPushButton(self.frame_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QRect(10, 190, 118, 35))
        self.pushButton_3.setStyleSheet(u"QPushButton{\n"
"	background-color: rgb(221, 221, 110);\n"
"	border: None;\n"
"}")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setFlat(False)
        self.producto = QPushButton(self.centralwidget)
        self.producto.setObjectName(u"producto")
        self.producto.setEnabled(False)
        self.producto.setGeometry(QRect(40, 290, 51, 51))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(True)
        font3.setWeight(75)
        self.producto.setFont(font3)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 260, 91, 21))
        self.producto_2 = QPushButton(self.centralwidget)
        self.producto_2.setObjectName(u"producto_2")
        self.producto_2.setEnabled(False)
        self.producto_2.setGeometry(QRect(100, 290, 51, 51))
        self.producto_2.setFont(font3)
        self.producto_2.setStyleSheet(u"")
        self.producto_3 = QPushButton(self.centralwidget)
        self.producto_3.setObjectName(u"producto_3")
        self.producto_3.setEnabled(False)
        self.producto_3.setGeometry(QRect(160, 290, 51, 51))
        self.producto_3.setFont(font3)
        self.producto_3.setStyleSheet(u"")
        self.producto_4 = QPushButton(self.centralwidget)
        self.producto_4.setObjectName(u"producto_4")
        self.producto_4.setEnabled(False)
        self.producto_4.setGeometry(QRect(220, 290, 51, 51))
        self.producto_4.setFont(font3)
        self.producto_4.setStyleSheet(u"")
        self.producto_5 = QPushButton(self.centralwidget)
        self.producto_5.setObjectName(u"producto_5")
        self.producto_5.setEnabled(False)
        self.producto_5.setGeometry(QRect(280, 290, 51, 51))
        self.producto_5.setFont(font3)
        self.producto_5.setStyleSheet(u"")
        self.producto_6 = QPushButton(self.centralwidget)
        self.producto_6.setObjectName(u"producto_6")
        self.producto_6.setEnabled(False)
        self.producto_6.setGeometry(QRect(340, 290, 51, 51))
        self.producto_6.setFont(font3)
        self.producto_6.setStyleSheet(u"")
        self.producto_7 = QPushButton(self.centralwidget)
        self.producto_7.setObjectName(u"producto_7")
        self.producto_7.setEnabled(False)
        self.producto_7.setGeometry(QRect(400, 290, 51, 51))
        self.producto_7.setFont(font3)
        self.producto_7.setStyleSheet(u"")
        self.producto_8 = QPushButton(self.centralwidget)
        self.producto_8.setObjectName(u"producto_8")
        self.producto_8.setEnabled(False)
        self.producto_8.setGeometry(QRect(460, 290, 51, 51))
        self.producto_8.setFont(font3)
        self.producto_8.setStyleSheet(u"")
        self.producto_9 = QPushButton(self.centralwidget)
        self.producto_9.setObjectName(u"producto_9")
        self.producto_9.setEnabled(False)
        self.producto_9.setGeometry(QRect(520, 290, 51, 51))
        self.producto_9.setFont(font3)
        self.producto_9.setStyleSheet(u"")
        self.producto_10 = QPushButton(self.centralwidget)
        self.producto_10.setObjectName(u"producto_10")
        self.producto_10.setEnabled(False)
        self.producto_10.setGeometry(QRect(580, 290, 51, 51))
        self.producto_10.setFont(font3)
        self.producto_10.setStyleSheet(u"")
        self.producto_14 = QPushButton(self.centralwidget)
        self.producto_14.setObjectName(u"producto_14")
        self.producto_14.setEnabled(False)
        self.producto_14.setGeometry(QRect(220, 350, 51, 51))
        self.producto_14.setFont(font3)
        self.producto_14.setStyleSheet(u"")
        self.producto_17 = QPushButton(self.centralwidget)
        self.producto_17.setObjectName(u"producto_17")
        self.producto_17.setEnabled(False)
        self.producto_17.setGeometry(QRect(400, 350, 51, 51))
        self.producto_17.setFont(font3)
        self.producto_17.setStyleSheet(u"")
        self.producto_20 = QPushButton(self.centralwidget)
        self.producto_20.setObjectName(u"producto_20")
        self.producto_20.setEnabled(False)
        self.producto_20.setGeometry(QRect(580, 350, 51, 51))
        self.producto_20.setFont(font3)
        self.producto_20.setStyleSheet(u"")
        self.producto_13 = QPushButton(self.centralwidget)
        self.producto_13.setObjectName(u"producto_13")
        self.producto_13.setEnabled(False)
        self.producto_13.setGeometry(QRect(160, 350, 51, 51))
        self.producto_13.setFont(font3)
        self.producto_13.setStyleSheet(u"")
        self.producto_15 = QPushButton(self.centralwidget)
        self.producto_15.setObjectName(u"producto_15")
        self.producto_15.setEnabled(False)
        self.producto_15.setGeometry(QRect(280, 350, 51, 51))
        self.producto_15.setFont(font3)
        self.producto_15.setStyleSheet(u"")
        self.producto_19 = QPushButton(self.centralwidget)
        self.producto_19.setObjectName(u"producto_19")
        self.producto_19.setEnabled(False)
        self.producto_19.setGeometry(QRect(520, 350, 51, 51))
        self.producto_19.setFont(font3)
        self.producto_19.setStyleSheet(u"")
        self.producto_12 = QPushButton(self.centralwidget)
        self.producto_12.setObjectName(u"producto_12")
        self.producto_12.setEnabled(False)
        self.producto_12.setGeometry(QRect(100, 350, 51, 51))
        self.producto_12.setFont(font3)
        self.producto_12.setStyleSheet(u"")
        self.producto_16 = QPushButton(self.centralwidget)
        self.producto_16.setObjectName(u"producto_16")
        self.producto_16.setEnabled(False)
        self.producto_16.setGeometry(QRect(340, 350, 51, 51))
        self.producto_16.setFont(font3)
        self.producto_16.setStyleSheet(u"")
        self.producto_11 = QPushButton(self.centralwidget)
        self.producto_11.setObjectName(u"producto_11")
        self.producto_11.setEnabled(False)
        self.producto_11.setGeometry(QRect(40, 350, 51, 51))
        self.producto_11.setFont(font3)
        self.producto_11.setStyleSheet(u"")
        self.producto_18 = QPushButton(self.centralwidget)
        self.producto_18.setObjectName(u"producto_18")
        self.producto_18.setEnabled(False)
        self.producto_18.setGeometry(QRect(460, 350, 51, 51))
        self.producto_18.setFont(font3)
        self.producto_18.setStyleSheet(u"")
        self.inicio_pushButton = QPushButton(self.centralwidget)
        self.inicio_pushButton.setObjectName(u"inicio_pushButton")
        self.inicio_pushButton.setGeometry(QRect(40, 410, 771, 23))
        self.lcdNumber = QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(653, 290, 161, 111))
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSegmentStyle(QLCDNumber.Flat)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(650, 260, 181, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 844, 26))
        self.menuVentana = QMenu(self.menubar)
        self.menuVentana.setObjectName(u"menuVentana")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuVentana.menuAction())
        self.menuVentana.addAction(self.actionSalir)

        self.retranslateUi(MainWindow)

        self.pushButton_2.setDefault(False)
        self.pushButton_3.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionSalir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
#if QT_CONFIG(shortcut)
        self.actionSalir.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Productor</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Estado:", None))
        self.label_estadoPro.setText(QCoreApplication.translate("MainWindow", u"Dormido", None))
        self.pushButton_4.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Consumidor</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Estado:", None))
        self.label_estadoCon.setText(QCoreApplication.translate("MainWindow", u"Dormido", None))
        self.pushButton_5.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Estados:</span></p><p><br/></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Dormido</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Trabajando</span></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">Espera</span></p></body></html>", None))
        self.pushButton.setText("")
        self.pushButton_2.setText("")
        self.pushButton_3.setText("")
        self.producto.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Productos</span></p></body></html>", None))
        self.producto_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.producto_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.producto_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.producto_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.producto_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.producto_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.producto_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.producto_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.producto_10.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.producto_14.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.producto_17.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.producto_20.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.producto_13.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.producto_15.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.producto_19.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.producto_12.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.producto_16.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.producto_11.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.producto_18.setText(QCoreApplication.translate("MainWindow", u"18", None))
        self.inicio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Iniciar", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Tiempo transcurrido</span></p></body></html>", None))
        self.menuVentana.setTitle(QCoreApplication.translate("MainWindow", u"Ventana", None))
    # retranslateUi

